name: Autodeploy to AWS TEST TEST TEST

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (stage or prod)?'
        required: true
        default: 'stage'
  push:
    branches:
      - stage
  release:
    types: [published]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/stage' || (github.event_name == 'workflow_dispatch' && github.event.inputs.releaseType == 'staging')
    environment: stage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: 'Create env file'
        run: |
          cat ${{ vars.ENV }}

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.releaseType == 'prod')
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: 'Create env file'
        run: |
          cat ${{ vars.ENV }}