name: Autodeploy to AWS TEST TEST TEST

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (stage or prod)?'
        required: true
        default: 'stage'
  push:
    branches:
      - stage
  release:
    types: [published]

jobs:
  set-variable:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.ENVIRONMENT }}

    steps:
    - name: Set Variable
      id: set-env
      run: |
        if [ "${{ github.event.inputs.releaseType }}" == "stage" ]; then
          echo "ENVIRONMENT=stage" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.inputs.releaseType }}" == "prod" ]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/stage" ]; then
          echo "ENVIRONMENT=stage" >> $GITHUB_OUTPUT
        elif [ "${{ github.event_name }}" == "release" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
        else
          echo "ENVIRONMENT=stage" >> $GITHUB_OUTPUT
        fi

    - name: Use Variable
      run: |
        echo "The environment is: ${{ steps.set-env.outputs.ENVIRONMENT }}"
  
  deploy:
    needs: set-variable
    runs-on: ubuntu-latest
    environment: ${{ needs.set-variable.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: 'Create env file'
        run: |
          cat ${{ vars.ENV }}